logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: INFO

spring:

  application:
    name: spring-oauth2

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-oauth2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:oauth2;Mode=MySQL

  profiles:
    group:
      local: jwt, database
    active: local